#dev version of config
server:
  port: 8083
#db config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: divyansh123
#    hikari:
#      pool-name: HikariCP
#      maximum-pool-size: 5
  #jpa and hibernate config
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true


